[2024-06-28T09:03:51.079+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:03:51.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script2 scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-06-28T09:03:51.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script2 scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-06-28T09:03:51.394+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T09:03:51.473+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script2> on 2023-12-24 00:00:00+00:00
[2024-06-28T09:03:51.529+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T09:03:51.537+0000] {standard_task_runner.py:63} INFO - Started process 463 to run task
[2024-06-28T09:03:51.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script2', 'scheduled__2023-12-24T00:00:00+00:00', '--job-id', '732', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpxzrz9l0i']
[2024-06-28T09:03:51.551+0000] {standard_task_runner.py:91} INFO - Job 732: Subtask task_from_script2
[2024-06-28T09:03:51.829+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script2 scheduled__2023-12-24T00:00:00+00:00 [running]> on host 1d2e3c34485f
[2024-06-28T09:03:52.391+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script2' AIRFLOW_CTX_EXECUTION_DATE='2023-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-24T00:00:00+00:00'
[2024-06-28T09:03:52.406+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T09:03:52.566+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T09:03:52.569+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script2.py", line 17, in function_from_script2
    y = df['on_ground'].astype(int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6534, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 616, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/dtypes/astype.py", line 134, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
[2024-06-28T09:03:52.623+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_sample_dag, task_id=task_from_script2, run_id=scheduled__2023-12-24T00:00:00+00:00, execution_date=20231224T000000, start_date=20240628T090351, end_date=20240628T090352
[2024-06-28T09:03:52.667+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 732 for task task_from_script2 (cannot convert float NaN to integer; 463)
[2024-06-28T09:03:52.723+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:03:52.793+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:03:52.798+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
