[2024-06-28T14:03:28.909+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T14:03:29.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:05:00+00:00 [queued]>
[2024-06-28T14:03:29.091+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:05:00+00:00 [queued]>
[2024-06-28T14:03:29.098+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-28T14:03:29.161+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script1> on 2023-08-16 02:05:00+00:00
[2024-06-28T14:03:29.222+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1468) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T14:03:29.229+0000] {standard_task_runner.py:63} INFO - Started process 1539 to run task
[2024-06-28T14:03:29.232+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script1', 'scheduled__2023-08-16T02:05:00+00:00', '--job-id', '1814', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpi7fju3qz']
[2024-06-28T14:03:29.239+0000] {standard_task_runner.py:91} INFO - Job 1814: Subtask task_from_script1
[2024-06-28T14:03:29.426+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T02:05:00+00:00 [running]> on host 81089ac3a69d
[2024-06-28T14:03:29.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-16T02:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-16T02:05:00+00:00'
[2024-06-28T14:03:29.773+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T14:03:29.778+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T14:03:29.779+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script1.py", line 10, in function_from_script1
    response = requests.get(url)
                            ^^^
NameError: name 'url' is not defined
[2024-06-28T14:03:29.828+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=my_sample_dag, task_id=task_from_script1, run_id=scheduled__2023-08-16T02:05:00+00:00, execution_date=20230816T020500, start_date=20240628T140329, end_date=20240628T140329
[2024-06-28T14:03:29.865+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1814 for task task_from_script1 (name 'url' is not defined; 1539)
[2024-06-28T14:03:29.898+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T14:03:29.960+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T14:03:29.972+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
