[2024-06-28T08:57:50.798+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-12-28T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
