[2024-06-28T14:02:45.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T14:02:45.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-04T00:20:00+00:00 [queued]>
[2024-06-28T14:02:45.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-04T00:20:00+00:00 [queued]>
[2024-06-28T14:02:45.358+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T14:02:45.379+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script1> on 2023-08-04 00:20:00+00:00
[2024-06-28T14:02:45.389+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T14:02:45.391+0000] {standard_task_runner.py:63} INFO - Started process 1387 to run task
[2024-06-28T14:02:45.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script1', 'scheduled__2023-08-04T00:20:00+00:00', '--job-id', '1807', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbg71mgyj']
[2024-06-28T14:02:45.392+0000] {standard_task_runner.py:91} INFO - Job 1807: Subtask task_from_script1
[2024-06-28T14:02:45.457+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-04T00:20:00+00:00 [running]> on host 81089ac3a69d
[2024-06-28T14:02:45.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-04T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-04T00:20:00+00:00'
[2024-06-28T14:02:45.578+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T14:02:45.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T14:02:45.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script1.py", line 10, in function_from_script1
    response = requests.get(url)
                            ^^^
NameError: name 'url' is not defined
[2024-06-28T14:02:45.592+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_sample_dag, task_id=task_from_script1, run_id=scheduled__2023-08-04T00:20:00+00:00, execution_date=20230804T002000, start_date=20240628T140245, end_date=20240628T140245
[2024-06-28T14:02:45.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1807 for task task_from_script1 (name 'url' is not defined; 1387)
[2024-06-28T14:02:45.655+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T14:02:45.684+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T14:02:45.687+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
